I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 115, in script
    mc "That was close..."
Exception: Sayer 'mc' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 115, in script
    mc "That was close..."
  File "C:\Program Files (x86)\renyp\renpy-8.0.0-sdk\renpy\ast.py", line 861, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Program Files (x86)\renyp\renpy-8.0.0-sdk\renpy\ast.py", line 754, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mc' is not defined.

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.0.22062402
Creative_Coding_Pruefung 1.0
Sat Jul  9 20:28:32 2022
